### ISSUE TITLE
Make sure all config options are well-documented

### ISSUE THREAD

**Issue by paulstraw** [imgix/imgix-core-js#13]

**Comment by oyeanuj** [comment]
@paulstraw Coming in trying to understand the library and saw this already opened :) Is this still on the radar?

**Comment by paulstraw** [comment]
Hey @oyeanuj, I wouldn't be the person to ask anymore, as I left imgix last year. Sorry!

**Comment by jayeb** [comment]
It is now! I'm not sure when I'll have time to update this documentation, @oyeanuj, but if you have any specific questions I can help with right now, just write in to support@imgix.com and I'll grab your ticket.
