### ISSUE TITLE
Signature broken beyond 0.2.1 (or 0.2.4)

### ISSUE THREAD

**Issue by mwawrusch** [imgix/imgix-core-js#15]
Hi guys,
I get arbitrary and wrong signature values when using 0.3.0), it works with 0.2.1 though - might be something to check out.

**Comment by paulstraw** [comment]
Hey @mwawrusch, are you still seeing this issue in 1.0.3?

**Comment by paulstraw** [comment]
I'm going to close this issue, as I haven't been able to replicate it. Feel free to reopen if you're still seeing this as of `1.0.3`, though!
