### ISSUE TITLE
Direct upload

### ISSUE THREAD

**Issue by anaibol** [imgix/imgix-core-js#17]
Hi, I really like many features of Imgix. I am currently using Cloudinary, with a poor service and support only because of the upload feature.
I want to use Imgix to upload multiple images at the same time directly from my backend to Imgix, no s3, no webfolder, like I do on cloudinary.
Is that possible? Thanks!

**Comment by paulstraw** [comment]
Hey @anaibol. We don't currently offer image hosting directly, but can easily integrate with just about whatever service it's easiest to have your backend upload to. I'm going to close this issue as it's not specific to imgix-core-js, but I'm happy to chat more if you want in our community Slack! http://slack.imgix.com

-paul
