### ISSUE TITLE
Online docs don't match latest version

### ISSUE THREAD

**Issue by namuol** [imgix/imgix-core-js#18]
The quick setup documentation [found here](https://docs.imgix.com/developer-tools/client-libraries/nodejs) shows the following initialization snippet:

![](https://i.gyazo.com/291e9e5fffdcd562805b0ac59f8b118b.png)

However, this doesn't match the latest api, which requires an object of named parameters, like so:

```js
new ImgixClient({
  host: 'https://brewpublik.imgix.net',
  secureURLToken: '1ekdu9DlZNArO7Sk',
});
```

Took me a minute to figure out what I was doing wrong, but it'd be easy to fix. :beers:

**Comment by kellysutton** [comment]
Hi @namuol, 

Thanks for pointing this out! We've pushed a fix.

**Comment by namuol** [comment]
That was quick -- thanks!
