### ISSUE TITLE
Expires params?

### ISSUE THREAD

**Issue by luminous8** [imgix/imgix-core-js#191]
Hi,

I'm trying to setup my images with Imgix and I can't find how to setup the expires params correctly with the lib.

My code looks like this
```
const in5min = new Date(new Date().getTime() + 5 * 60 * 1000).getTime();

 var srcSet = client.buildSrcSet(
    "img.png",
    {
      w: 720,
      h: 120,
      expires: in5min,
      auto: "compress",
    },
    { maxWidth: 1000 }
  );

```
The generated urls looks like this:
`https://XXXX.imgix.net/img.png?ixlib=js-2.3.2&w=2000&expires=1606291871320&auto=compress&dpr=5&q=20&s=91a2d83ca17c26b4a880e0366f7447a4
`
And I can visit the path after the date specified in the expires params, it still works.

Any way to fix this?

Thanks!

**Comment by ericdeansanchez** [comment]
Hey @luminous8  👋 thanks for opening this PR!

The `expires` parameter [expects a UNIX timestamp in seconds](https://docs.imgix.com/apis/rendering/expiration/expires), whereas the [`getTime()` function returns the number of milliseconds](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTime).

So for your specific case, you could modify your _future time_ to be reflected in seconds as well:

```js
Math.floor(new Date(new Date().getTime() + 5 * 60 * 1000).getTime() / 1000.0)
```

**Comment by ericdeansanchez** [comment]
I'm going to go ahead and close this. Please feel free to respond back here if you have any more questions, thank you!
