### ISSUE TITLE
Incorrect url encoding

### ISSUE THREAD

**Issue by MichaelMag** [imgix/imgix-core-js#24]
Origin file name: "download copy #1-[mike].png"
S3 URL: https://s3-us-west-2.amazonaws.com/testBuck/download%20copy%20%231-%5Bmike%5D.png

`ImgixClient.buildURL(fileName, params)` should return:  "https://some-prefix.imgix.net/download%20copy%20%231-%5Bmike%5D.png?s=52dd73573bffb0948d49118f30ea9218
but the result is: https://some-prefix.imgix.net/download%20copy%20#1-%5Bmike%5D.png?s=12c9ae700d245a639334a2763c93c304

So, the result url is incorrect because of `#` in the url and imgix return _URI signature match failed_.
I found that the problem is here: 
https://github.com/imgix/imgix-core-js/blob/1.0.5/src/imgix-core-js.js#L65-L83

**Comment by jayeb** [comment]
@MichaelMag Sorry about the delay here--up until today I wasn't actually watching this repo like I thought I was 😞 . Will take a look this week.

**Comment by jayeb** [comment]
Additional, related issue: if a URL is passed in "partially" encoded (for example, if there's a query parameter with an encoded value, but the URL is otherwise unencoded), the decode step on L70 is harming the input URL.

**Comment by jayeb** [comment]
Just released 1.0.6, which fixes this issue.
