### ISSUE TITLE
Errors when using library client-side.

### ISSUE THREAD

**Issue by whaaaley** [imgix/imgix-core-js#32]
I'm following the docs exactly yet I get two errors:
`Uncaught TypeError: Cannot read property 'Base64' of undefined`
`Uncaught ReferenceError: ImgixClient is not defined`

I'm including the library like this:
`<script defer src='https://unpkg.com/imgix-core-js@1.1.1/dist/imgix-core-js.min.js'></script>`

**Comment by jayeb** [comment]
Yup, this library has two dependencies that you need to include as well. They're listed in `package.json`:

```
"js-base64": "^2.1.9",
"md5": "^2.2.1"
```

If you install the package via Bower or NPM those packages will be installed automatically. I'm not familiar with unpkg, but I assume they should have a mechanism somewhere in their service that will allow you to include dependencies as well.
