### ISSUE TITLE
Readme is out of sync with latest npm version

### ISSUE THREAD

**Issue by mitchellbutler** [imgix/imgix-core-js#35]
Based on the readme the `host` setting is deprecated in favour of the `domains` setting. The latest version of this package on npm will throw an error if the `host` is not provided. Ideally changes like this, including to the readme, would be made in feature branches and pulled into master as part of a release to avoid confusion.

**Comment by hashknot** [comment]
Hi @mitchellbutler,

I am sorry about the confusion. I just released v1.2.0. In the future, we'll make sure the GitHub repository and the NPM package is up-to-date.

Feel free to close the issue if v1.2.0 is working fine for you.

**Comment by mitchellbutler** [comment]
Just updated to the latest version and confirmed it's working. Thanks!
