### ISSUE TITLE
Typings

### ISSUE THREAD

**Issue by hennessyevan** [imgix/imgix-core-js#50]
Would it be possible to get some typescript typings for this package, either in the repo or on definitely typed?

**Comment by sherwinski** [comment]
Hey @hennessyevan, we've been getting more requests for this (and our other JS projects) lately, so it's definitely something we're planning to look into in the near future. I don't have an exact timeline at the moment but I'll be sure to update you when we get to it.

**Comment by gatherben** [comment]
+1 on typings!

**Comment by guanzo** [comment]
There should be typings for the `param` argument to `buildURL`.

**Comment by sherwinski** [comment]
Hey @guanzo,

I agree that `params` deserves better typings. As a team, we are planning to pull in [imgix-url-params](https://github.com/imgix/imgix-url-params) as a dependency from which these definitions can be robustly constructed. This will help account for changes to the rendering API, as well as any new parameters that get added. To that end, `params` was assigned a very rudimentary type just to start out, but we expect to start work on pulling in these definitions in the near future. Hope that helps.

**Comment by guanzo** [comment]
Ok great, thanks for clarifying. Sorry I called you guys lazy!

**Comment by robinJonsson** [comment]
The typings for `buildURL` is still missing.
https://github.com/imgix/js-core/blob/v3.3.0-beta.1/src/index.mjs#L43

**Comment by sherwinski** [comment]
Hey @robinJonsson, the typings should be included in the project's [index.d.ts](https://github.com/imgix/js-core/blob/main/dist/imgix-js-core.d.ts#L11) file.

<img width="623" alt="Screen Shot 2021-04-09 at 12 52 34 PM" src="https://user-images.githubusercontent.com/15919091/114214982-e4652c80-9919-11eb-9a5f-e3864284bbb1.png">

**Comment by robinJonsson** [comment]
Hi @sherwinski, I meant that the `params` argument is still pointing to an empty object. It would be great if `params` had the correct types.

**Comment by sherwinski** [comment]
Ah sorry about that, I misunderstood your first comment. Apologies for the delays on this feature, but we have finally set aside time to build this out later this year.
