### ISSUE TITLE
Typescript and `@types/node` should be devDependencies.

### ISSUE THREAD

**Issue by rockon999** [imgix/imgix-core-js#76]
From [this pull request](https://github.com/imgix/imgix-core-js/pull/64/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R17) onward `imgix-core-js` depends on `typescript` and `@types/node`.

As these are not run-time dependencies they should be under `devDependencies`.

Because these are under `dependencies` npm/yarn believes that `imgix-core-js` needs those versions of `typescript` and `@types/node` to _run_ which means you're pulling in potentially conflicting versions of Typescript and the nodes type package whenever a client imports imgix-core-js via `yarn add imgix-core-js` or `npm install imgix-core-js`.

I ran into this while upgrading to Typescript 3.7 as `imgix-core-js` was breaking my build due to its dependency on Typescript 3.6.

**Comment by sherwinski** [comment]
Thanks for pointing this out @rockon999. I'll get on changing that now.
